IF db_id('College1en') IS NULL CREATE DATABASE College1en;
GO

-- creation des tables

USE College1en;

CREATE TABLE Programs (
  ProgId VARCHAR(5) NOT NULL PRIMARY KEY,
  ProgName VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Courses (
  CId VARCHAR(7) NOT NULL PRIMARY KEY,
  CName VARCHAR(50) NOT NULL,
  ProgId VARCHAR(5) NOT NULL,
  FOREIGN KEY (ProgId) REFERENCES Programs(ProgId) ON DELETE CASCADE ON UPDATE CASCADE
);
GO

CREATE TABLE Students (
  StId VARCHAR(10) NOT NULL PRIMARY KEY,
  StName VARCHAR(50) NOT NULL,
  ProgId VARCHAR(5) NOT NULL,
  FOREIGN KEY (ProgId) REFERENCES Programs(ProgId) ON DELETE NO ACTION ON UPDATE CASCADE
);
GO

CREATE TABLE Enrollments (
  StId VARCHAR(10) NOT NULL,
  CId VARCHAR(7) NOT NULL,
  FinalGrade INT,
  PRIMARY KEY (StId, CId),
  FOREIGN KEY (StId) REFERENCES Students(StId) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CId) REFERENCES Courses(CId) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO